name: Code Quality

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install rye
        uses: eifinger/setup-rye@v1
      - name: Install dependencies
        run: rye sync
      - name: Linting
        uses: chartboost/ruff-action@v1
      - name: Testing
        run: rye run pytest --cov-report term-missing

